---
title: "diabetes"
author: "DW"
date: "2025-04-10"
output: html_document
---

```{r}
library(data.table)
library(dplyr)
library(corrplot)
```

```{r}
df <- read.csv("diabetes.csv")
head(df)
```

```{r}
summary(df)

```

```{r}
df_filtered <- df %>%
  filter(across(c(BMI, Insulin, SkinThickness, BloodPressure, Glucose), ~ .x != 0))
df_filtered %>%
  rename(DPF = DiabetesPedigreeFunction) -> df_model
mat_cor <- cor(df_model)
corrplot(mat_cor)
head(df_filtered)

```

```{r}
# Dopasowanie modelu regresji logistycznej

model <- glm(Outcome ~ Glucose + BMI + DPF + Age,
                   data = df_model, family = binomial)

# Podsumowanie wyników modelu
summary(model)
plot(model)
```
```{r}
# Obliczenie ilorazów szans
exp(coef(model))

```
```{r}
# Predykcja prawdopodobieństw dla oryginalnych danych
predicted_prob <- predict(model, type = "response")

# Zamiana prawdopodobieństw na klasy (przy progu 0.5)
predicted_class <- ifelse(predicted_prob > 0.5, "cukrzyca", "brak cukrzycy")

# Wyświetlenie pierwszych kilku wartości
head(predicted_class)

```
```{r}
# Macierz pomyłek
table(Predicted = predicted_class, Actual = df_model$Outcome)

```

```{r}

set.seed(123)
train_idx <- sample(1:nrow(df_model), 0.7*nrow(df_model))
train <- df_model[train_idx,]
test <- df_model[-train_idx,]
final_model <- glm(Outcome ~ Glucose + BMI + DPF + Age, data = train, family = binomial)
predictions <- predict(final_model, newdata = test)
summary(final_model)
```

```{r}
df_filtered$Predicted <- round(predict(final_model,
                                       newdata = df_model,
                                       type = "response"),2)
head(df_filtered[c("Outcome", "Predicted")], 10)

```

```{r}
library(ggplot2)
ggplot(df_filtered, aes(x = factor(Outcome), y = Predicted)) +
  geom_jitter(
    aes(color = "Przewidywane"), 
    width = 0.1, 
    height = 0, 
    size = 2, 
    alpha = 0.7
  ) +
  geom_point(
    aes(y = Outcome, color = "Rzeczywiste"), 
    size = 2, 
    alpha = 0.3,
    position = position_jitter(width = 0.0)
  ) +
  scale_color_manual(
    values = c("Rzeczywiste" = "#00cc44", "Przewidywane" = "#ff4444"),
    name = "Legenda"
  ) +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey40") +
  labs(
    title = "Porównanie wartości rzeczywistych i przewidywanych",
    x = "Rzeczywista klasa",
    y = "Przewidywane prawdopodobieństwo"
  ) +
  scale_y_continuous(breaks = seq(0, 1, 0.25)) +
  theme_minimal() +
  theme(legend.position = "top")
```
